export const GET_CLIENTS_LIST = 'GET_CLIENTS_LIST';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILURE = 'GET_CLIENTS_FAILURE';
export const CLEAR_CLIENTS_DATA = 'CLEAR_CLIENTS_DATA';
export const SET_CURRENT_CLIENT = 'SET_CURRENT_CLIENT';
export const SEND_UPDATED_CLIENT_DATA = 'SEND_UPDATED_CLIENT_DATA';
